Hello, I am  2
Hello, I am  1
Hello, I am  0
data sent to node 1
data received on node 1 from node 0
data sent to node 2
data received on node 2 from node 0
requested_nodes_list
[[], [], []]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0,    0,    0,  ..., 2649, 2649, 2649],
        [ 335,  980, 2699,  ...,   85,  320,  776]]) torch.Size([2, 5932])
world size 3
request nodes: 0
request nodes: 0
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 183, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 169, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 134, in forward
    x = self.conv1(x, edge_index)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 19, in forward
    return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 310, in propagate
    size, kwargs)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 202, in __collect__
    j if arg[-2:] == '_j' else i)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 171, in __lift__
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self
requested_nodes_list
[[], [0, 5, 8, 14, 15, 23, 26, 32, 33, 35, 40, 41, 43, 45, 51, 56, 58, 73, 75, 78, 79, 80, 85, 86, 89, 94, 99, 100, 102, 106, 108, 126, 128, 132, 143, 145, 146, 152, 158, 162, 169, 183, 190, 196, 198, 201, 202, 203, 208, 217, 219, 225, 227, 230, 234, 239, 248, 253, 255, 262, 264, 270, 272, 279, 308, 310, 313, 317, 320, 325, 327, 329, 332, 340, 342, 355, 357, 358, 366, 378, 379, 382, 384, 387, 388, 392, 393, 394, 395, 401, 405, 425, 430, 437, 439, 440, 441, 442, 448, 454, 455, 459, 464, 468, 482, 487, 489, 493, 496, 503, 505, 506, 508, 512, 515, 516, 523, 524, 525, 530, 534, 542, 547, 555, 556, 557, 571, 579, 586, 591, 594, 603, 604, 609, 611, 612, 624, 626, 630, 645, 655, 661, 665, 667, 674], [681, 684, 686, 687, 694, 695, 701, 708, 710, 723, 728, 730, 734, 750, 752, 756, 760, 763, 765, 766, 768, 775, 776, 777, 782, 791, 792, 794, 797, 800, 801, 803, 804, 805, 806, 807, 813, 820, 822, 823, 845, 846, 847, 848, 858, 872, 878, 884, 887, 888, 893, 894, 895, 896, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 912, 916, 919, 928, 930, 931, 932, 942, 944, 947, 949, 950, 951, 957, 958, 959, 967, 970, 980, 988, 994, 995, 996, 997, 998, 999, 1005, 1006, 1008, 1014, 1017, 1019, 1020, 1025, 1029, 1032, 1035, 1044, 1046, 1049, 1053, 1058, 1061, 1062, 1072, 1076, 1085, 1089, 1092, 1094, 1099, 1104, 1119, 1137, 1142, 1145, 1164, 1166, 1167, 1194, 1198, 1208, 1213, 1214, 1220, 1231, 1257, 1270, 1287, 1303, 1306, 1316, 1317, 1347]]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0, 1354, 1354,  ..., 2649, 2649, 2649],
        [2699, 1355, 1660,  ...,  320,  776, 2650]]) torch.Size([2, 5444])
world size 3
request nodes: 145
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 183, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 169, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 114, in forward
    requested_nodes_list = recv_object(src = 1)
  File "/home/dsys2352/DSassignment/GCN/utils.py", line 284, in recv_object
    dist.recv(size, src=src)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 850, in recv
    pg.recv([tensor], src, tag).wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [10.141.0.2]:33666
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 1096116
srun: error: node002: task 1: Exited with exit code 1
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 290539
srun: error: node024: task 2: Exited with exit code 1
