Hello, I am  2
Hello, I am  1
Hello, I am  0
data sent to node 1
data received on node 1 from node 0
Range
[range(0, 677), range(677, 1354)]
data sent to node 2
data received on node 2 from node 0
requested_nodes_list
[[], [], []]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0,    0,    0,  ..., 2507, 2507, 2507],
        [ 368, 1104, 2587,  ...,   90,  345,  847]]) torch.Size([2, 6366])
world size 3
request nodes: 0
request nodes: 0
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 185, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 171, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 136, in forward
    x = self.conv1(x, edge_index)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 19, in forward
    return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 310, in propagate
    size, kwargs)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 202, in __collect__
    j if arg[-2:] == '_j' else i)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 171, in __lift__
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self
Range
[range(0, 677), range(677, 1354)]
requested_nodes_list
[[], [0, 1, 2, 4, 5, 7, 10, 15, 18, 21, 23, 28, 31, 32, 33, 34, 35, 38, 42, 43, 45, 51, 53, 54, 57, 60, 62, 68, 69, 73, 74, 78, 79, 80, 81, 84, 87, 90, 91, 96, 98, 102, 104, 105, 107, 108, 109, 111, 113, 115, 119, 120, 124, 132, 138, 140, 141, 143, 145, 146, 149, 153, 154, 155, 159, 163, 165, 168, 169, 170, 171, 173, 175, 181, 186, 189, 190, 192, 194, 195, 199, 203, 204, 206, 209, 210, 212, 213, 214, 216, 217, 219, 223, 224, 226, 229, 231, 235, 238, 241, 245, 250, 251, 252, 254, 255, 258, 260, 262, 264, 265, 268, 269, 272, 274, 275, 278, 279, 281, 284, 285, 288, 289, 290, 292, 294, 298, 300, 301, 302, 306, 311, 313, 314, 315, 320, 325, 327, 329, 331, 333, 334, 335, 336, 337, 338, 339, 341, 342, 345, 347, 350, 352, 353, 356, 357, 358, 359, 360, 362, 363, 366, 369, 370, 371, 372, 374, 384, 388, 389, 391, 400, 404, 405, 406, 408, 413, 414, 416, 417, 420, 422, 423, 424, 425, 427, 431, 432, 435, 436, 437, 438, 440, 441, 442, 443, 444, 446, 463, 464, 470, 475, 476, 477, 485, 486, 487, 490, 492, 493, 494, 495, 505, 509, 515, 517, 518, 525, 527, 535, 540, 541, 545, 546, 549, 550, 551, 553, 555, 558, 559, 560, 564, 569, 570, 574, 575, 578, 579, 581, 582, 587, 589, 592, 594, 595, 600, 601, 603, 606, 609, 612, 614, 615, 620, 621, 623, 624, 626, 632, 635, 636, 638, 646, 647, 655, 659, 661, 662, 665, 668, 670], [680, 682, 683, 685, 686, 688, 689, 690, 696, 698, 699, 702, 705, 711, 712, 713, 717, 722, 727, 729, 730, 738, 739, 740, 741, 747, 751, 752, 756, 760, 763, 764, 772, 773, 774, 776, 778, 779, 781, 784, 785, 786, 787, 790, 792, 793, 794, 796, 799, 800, 807, 808, 809, 812, 813, 818, 821, 822, 823, 824, 828, 829, 830, 831, 843, 844, 847, 848, 856, 861, 862, 863, 864, 865, 869, 872, 875, 876, 877, 878, 889, 891, 902, 907, 910, 917, 918, 920, 927, 928, 931, 934, 935, 936, 937, 940, 944, 946, 948, 956, 962, 963, 966, 969, 971, 973, 975, 977, 980, 982, 984, 986, 990, 992, 993, 996, 997, 998, 1001, 1004, 1005, 1006, 1008, 1009, 1012, 1014, 1016, 1019, 1020, 1022, 1026, 1028, 1033, 1034, 1035, 1040, 1046, 1057, 1059, 1060, 1063, 1066, 1072, 1074, 1076, 1077, 1088, 1091, 1092, 1093, 1104, 1114, 1117, 1121, 1122, 1126, 1127, 1132, 1133, 1136, 1138, 1139, 1140, 1141, 1142, 1143, 1146, 1150, 1151, 1152, 1153, 1160, 1162, 1163, 1172, 1174, 1175, 1177, 1178, 1184, 1186, 1188, 1190, 1193, 1194, 1195, 1196, 1197, 1200, 1204, 1208, 1209, 1215, 1220, 1231, 1236, 1237, 1238, 1241, 1242, 1245, 1252, 1255, 1258, 1259, 1262, 1270, 1279, 1280, 1282, 1283, 1284, 1289, 1291, 1293, 1299, 1301, 1308, 1312, 1313, 1314, 1319, 1330, 1333, 1336, 1341, 1346, 1349, 1353]]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0, 1354, 1354,  ..., 2507, 2507, 2507],
        [2587, 1355, 1626,  ...,  345,  847, 2508]]) torch.Size([2, 5742])
world size 3
request nodes: 272
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 185, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 171, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 116, in forward
    requested_nodes_list = recv_object(src = 1)
  File "/home/dsys2352/DSassignment/GCN/utils.py", line 285, in recv_object
    dist.recv(size, src=src)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 850, in recv
    pg.recv([tensor], src, tag).wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [10.141.0.2]:10160
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 1096804
srun: error: node002: task 1: Exited with exit code 1
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 291166
srun: error: node024: task 2: Exited with exit code 1
