Hello, I am  2
Hello, I am  1
Hello, I am  0
num_nodes 2708 2708
data sent to node 1
data received on node 1 from node 0
Range
[range(0, 677), range(677, 1354)]
data sent to node 2
data received on node 2 from node 0
requested_nodes_list
[[], [], []]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0,    0,    0,  ..., 2591, 2591, 2591],
        [ 362, 1028, 2674,  ...,   83,  338,  818]]) torch.Size([2, 5894])
world size 3
request nodes: 0
request nodes: 0
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 185, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 171, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 136, in forward
    x = self.conv1(x, edge_index)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 19, in forward
    return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 310, in propagate
    size, kwargs)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 202, in __collect__
    j if arg[-2:] == '_j' else i)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 171, in __lift__
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self
Range
[range(0, 677), range(677, 1354)]
requested_nodes_list
[[], [0, 1, 2, 4, 7, 8, 15, 17, 22, 25, 32, 34, 35, 36, 38, 45, 51, 53, 55, 58, 61, 64, 65, 70, 79, 83, 84, 85, 91, 92, 99, 101, 108, 111, 115, 118, 122, 127, 129, 130, 132, 137, 138, 148, 149, 160, 162, 167, 169, 174, 185, 186, 192, 193, 197, 201, 203, 211, 212, 213, 216, 228, 229, 233, 235, 240, 244, 249, 250, 252, 255, 261, 262, 269, 271, 272, 279, 280, 282, 283, 284, 291, 295, 296, 301, 307, 316, 327, 330, 336, 338, 340, 341, 342, 344, 352, 353, 356, 358, 365, 366, 371, 372, 375, 379, 381, 396, 397, 399, 401, 402, 405, 409, 410, 411, 412, 413, 414, 417, 421, 424, 430, 434, 449, 454, 459, 462, 463, 465, 475, 478, 480, 481, 487, 495, 500, 506, 519, 520, 529, 534, 536, 540, 541, 542, 544, 546, 547, 556, 557, 562, 566, 570, 574, 575, 579, 580, 586, 587, 588, 598, 603, 604, 606, 611, 612, 621, 622, 630, 634, 635, 638, 643, 648, 654, 655, 658, 666, 667, 670, 672, 675, 676], [691, 697, 703, 705, 708, 711, 717, 719, 728, 731, 733, 737, 749, 752, 753, 756, 764, 766, 767, 772, 773, 774, 782, 795, 799, 801, 803, 807, 808, 815, 818, 831, 832, 841, 842, 844, 848, 849, 851, 853, 855, 863, 865, 868, 871, 873, 876, 878, 883, 888, 891, 895, 903, 905, 911, 912, 920, 922, 924, 927, 929, 931, 932, 933, 943, 944, 947, 951, 952, 956, 958, 961, 964, 970, 975, 984, 989, 994, 996, 1008, 1015, 1016, 1017, 1018, 1019, 1028, 1031, 1037, 1040, 1044, 1045, 1049, 1054, 1055, 1056, 1075, 1076, 1086, 1087, 1090, 1093, 1094, 1105, 1112, 1113, 1114, 1115, 1131, 1132, 1134, 1135, 1140, 1145, 1149, 1150, 1159, 1160, 1174, 1175, 1176, 1188, 1189, 1197, 1203, 1208, 1210, 1218, 1220, 1227, 1228, 1229, 1231, 1236, 1247, 1257, 1259, 1260, 1273, 1280, 1281, 1283, 1285, 1292, 1295, 1302, 1303, 1308, 1317, 1318, 1320, 1329, 1337, 1341, 1344]]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0, 1354, 1354,  ..., 2591, 2591, 2591],
        [2674, 1355, 1634,  ...,  338,  818, 2592]]) torch.Size([2, 5722])
world size 3
request nodes: 183
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 185, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 171, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 116, in forward
    requested_nodes_list = recv_object(src = 1)
  File "/home/dsys2352/DSassignment/GCN/utils.py", line 287, in recv_object
    dist.recv(size, src=src)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 850, in recv
    pg.recv([tensor], src, tag).wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [10.141.0.2]:33717
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 1096947
srun: error: node002: task 1: Exited with exit code 1
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 291286
srun: error: node024: task 2: Exited with exit code 1
