Hello, I am  2
Hello, I am  1
Hello, I am  0
data sent to node 1
data received on node 1 from node 0
Range
[range(0, 677), range(677, 1354)]
data sent to node 2
data received on node 2 from node 0
requested_nodes_list
[[], [], []]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0,    0,    0,  ..., 2634, 2634, 2634],
        [ 343,  999, 2699,  ...,   81,  319,  784]]) torch.Size([2, 5924])
world size 3
request nodes: 0
request nodes: 0
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 185, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 171, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 136, in forward
    x = self.conv1(x, edge_index)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 19, in forward
    return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 310, in propagate
    size, kwargs)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 202, in __collect__
    j if arg[-2:] == '_j' else i)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 171, in __lift__
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self
Range
[range(0, 677), range(677, 1354)]
requested_nodes_list
[[], [0, 4, 7, 8, 15, 23, 24, 32, 34, 35, 37, 38, 45, 52, 54, 57, 58, 62, 65, 66, 67, 72, 77, 81, 82, 88, 89, 92, 99, 101, 103, 107, 109, 114, 119, 120, 126, 134, 137, 145, 147, 153, 159, 167, 170, 173, 180, 182, 188, 189, 192, 202, 204, 210, 212, 220, 222, 224, 225, 230, 231, 232, 234, 242, 250, 253, 255, 260, 261, 265, 269, 276, 283, 284, 290, 292, 294, 296, 301, 306, 309, 314, 317, 319, 320, 321, 322, 323, 325, 334, 345, 347, 351, 355, 360, 361, 377, 378, 380, 383, 392, 393, 394, 395, 396, 400, 404, 408, 411, 416, 443, 452, 459, 460, 468, 472, 478, 483, 485, 486, 490, 504, 505, 514, 519, 520, 530, 531, 533, 537, 545, 548, 556, 562, 569, 571, 578, 588, 591, 594, 597, 616, 623, 625, 634, 636, 644, 645, 647, 650, 652, 660, 663, 668, 670, 672, 675], [682, 687, 691, 693, 696, 706, 710, 727, 729, 733, 739, 744, 748, 749, 755, 765, 768, 770, 771, 779, 781, 784, 787, 790, 793, 798, 805, 808, 813, 814, 816, 817, 824, 826, 831, 833, 835, 838, 841, 845, 850, 862, 869, 873, 874, 877, 878, 888, 893, 894, 895, 906, 909, 913, 916, 917, 920, 923, 926, 930, 931, 936, 941, 950, 951, 957, 958, 963, 977, 984, 985, 986, 987, 988, 989, 990, 991, 999, 1002, 1006, 1012, 1016, 1017, 1021, 1025, 1026, 1027, 1032, 1033, 1054, 1055, 1058, 1059, 1060, 1063, 1066, 1067, 1083, 1084, 1085, 1086, 1089, 1101, 1105, 1106, 1108, 1109, 1113, 1119, 1126, 1127, 1130, 1140, 1143, 1150, 1159, 1166, 1172, 1181, 1182, 1187, 1193, 1203, 1213, 1217, 1238, 1251, 1259, 1260, 1265, 1271, 1274, 1280, 1282, 1283, 1284, 1289, 1291, 1294, 1295, 1300, 1301, 1320, 1329, 1340, 1341]]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0, 1354, 1354,  ..., 2634, 2634, 2634],
        [2699, 1355, 1654,  ...,  319,  784, 2635]]) torch.Size([2, 5618])
world size 3
request nodes: 157
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 185, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 171, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 116, in forward
    requested_nodes_list = recv_object(src = 1)
  File "/home/dsys2352/DSassignment/GCN/utils.py", line 285, in recv_object
    dist.recv(size, src=src)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 850, in recv
    pg.recv([tensor], src, tag).wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [10.141.0.2]:20384
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 1096500
srun: error: node002: task 1: Exited with exit code 1
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 290884
srun: error: node024: task 2: Exited with exit code 1
